### ISSUE TITLE
Death Knight Talent Switch bug

### ISSUE THREAD

**Issue by Refurinn** [ProjectNelth/BugTracker#173]
Description: When switching talents as a Death Knight the actual switch cancels out the presence you're in leaving you in a state without an actual presence.

Current behaviour: Switching talents clears the presence aura.

Expected behaviour: Presence should stay as a active aura even after switching talents.

Links:

**Comment by afdruiprekje** [comment]
Link: https://streamable.com/86ag7s

**Comment by therealsmf** [comment]
https://youtu.be/XO7R_FQCiP4?t=81
footage from the original cata ptr, showing that presences do in fact fade when switching specs with dual spec. since there is no official patch note saying it got changed between then and 4.3.4, and in 2 hours i was not able to find anything regarding it either, im gonna assume its actually not a bug and working as intended.
