### ISSUE TITLE
[Tooltip only?] Elemental precision

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#184]
Description:
Increase spell damage by 1,2,3%.
Increase hit rating by 33, 66, 100% of spirit.

Current behaviour:
1. No damage benefit from this talent.
2. Hit rating actually drops from the first talent point into elemental precision.

![image](https://user-images.githubusercontent.com/58305537/71028616-a2d4c080-20db-11ea-8109-2eb1f132a906.png)

Expected behaviour:
Increase spell damage by 1,2,3%.
Increase hit rating by 33, 66, 100% of spirit.

**Comment by cryptid123** [comment]
This is one of several bugs that were found by a simple tooltip check.
After discovering that other spells have issues, I am marking every bug that was not dummy-tested.

**Comment by therealsmf** [comment]
elemental precision - increases fire, frost, nature damage by 1/2/3% and increases hit rating by 33/66/100% of spirit.

results			0/3	1/3	2/3	3/3

chain lightning		12321	12439	12561	12683
earth shock		5611	5671	5724	5779
flame shock initial	3127	3158	3189	3220
flame shock dot		1349	1362	1376	1389
fire nova		2641	2669	2688	2718
frost shock		5550	5606	5659	5722
lava burst		13512	13654	13780	13919
lightning bolt		13683	13817	13956	14095
magma totem		1025	1035	1045	1055
searing totem		1985	2017	2032	2043
thunderstorm		4309	4355	4388	4433
flametongue proc	1421	1435	1450	1464
frostbrand proc		1742	1759	1776	1794
lightning shield	3409	3443	3477	3511
unleash flame		5769	5818	5877	5934
unleash frost		5471	5534	5585	5640

scaling should be 1->1.01->1.02->1.03

simplified

chain lightning		1	1.010	1.019	1.029
earth shock		1	1.011	1.020	1.030
flame shock initial	1	1.010	1.020	1.030
flame shock dot		1	1.010	1.020	1.030
fire nova		1	1.011	1.018	1.029
frost shock		1	1.010	1.020	1.031
lava burst		1	1.011	1.020	1.030
lightning bolt		1	1.010	1.020	1.030
magma totem		1	1.010	1.020	1.029
searing totem		1	1.016	1.024	1.029
thunderstorm		1	1.011	1.018	1.029
flametongue proc	1	1.010	1.020	1.030
frostbrand proc		1	1.010	1.020	1.030
lightning shield	1	1.010	1.020	1.030
unleash flame		1	1.008	1.019	1.029
unleash frost		1	1.012	1.021	1.031


hit rating (1455 sp)	779	1153	1685	2234

spirit->hit: every item equipped individually boosts hit rating by 1/3rd of the spirit value correctly. it looks like theres a hidden drawback for picking only 1 or 2 points in this talent - by reducing the base hit rating value. since you cant have negative hit, its not shown in the character stats. as realistically nobody is going to put only 1 or 2 points into this talent (resto doesnt care about hit cap, and both dps specs go for 3/3 anyway), i dont think its worth investigating why this is the case, or if its a bug or not. the important part is that it works perfectly at 0/3 and 3/3.

searing totem: since the damage is only off by about half a percent, and even that is only noticable at 1/3 and 2/3, with the reasoning above we can conclude that we dont need to change anything about this talent.
