### ISSUE TITLE
[List] Eye of the Storm

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#279]
**Achievements have not been checked for this BG**

- ~~Flag is not "perfectly" centered.~~ fixed

- ~~If you die from falling when you join before a game(or by any means during waiting phase), you can /reload to walk around immune. You are technically dead and cannot interact with a flag or players, but you are a visible distraction/nuisance.~~ Indirectly fixed by correcting boundary.

**Comment by Saintagony** [comment]
Achievements:

- Eye of the Storm Victory - Good
- The Perfect Storm - Good
- Eye of the Storm Domination - Good
- Flurry - Good
- Stormtrooper - Currently is achieved after 4 kills instead of 5
- Storm Capper - Good
- Bound for Glory - Good
- Stormy Assassin - Good
- Take a Chill Pill - Can't Complete/Bugged
- Bloodthirsty Bersker - Good
- Storm glory - Good
- Eye of the Storm Veteran - Good

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/eye-of-the-storm-r91/
