### ISSUE TITLE
No'Kaled Axe Rogue procs

### ISSUE THREAD

**Issue by Akka3223** [ProjectNelth/BugTracker#352]
Description: 
According to wowhead ( https://www.wowhead.com/item=77188/nokaled-the-elements-of-death#comments )
comments, it should'nt proc on shiv, gouge and autoattack's offhand

Current behaviour:
Offhand Auto Attack - https://i.imgur.com/iI3zk7Z.jpeg
Gouge - https://i.imgur.com/nKy0Fms.jpeg
**^ - It even triple proc'd the axe proc on gouge wtf O.o**
Shiv - https://i.imgur.com/hJtr0ZC.jpeg
**^ - Triple proc on 6th hit again**
Im not sure if it should be able to proc from proc's 
Expected behaviour:
As stated in wowhead comments 
It does not proc of special abilities done with the other equipped weapon (e.g.  Shiv for Rogues).
It does not proc of Main Gauche (Combat Rogue Mastery).
It does not proc of auto-attacks of the other equipped weapon (off-hand in the case of rogues).

It only procs of its own auto-attacks and special abilities done with this weapon.

Links:

**Comment by therealsmf** [comment]
lightning strike and whirling maw are your trinkets. flameblast/iceblast/shadowblast are the axe procs, and they can double hit when you have 2 equipped because both of them proc at the same time, they also have no icd. its also not just a rogue problem, i assume other classes have offhand abilities that trigger the proc when they shouldnt.

**Comment by PN-Cryptid** [comment]
Fixed in patch 56.
