### ISSUE TITLE
Dancing Rune Weapon Threat Generation

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#353]
Description: Currently generates threat.

Expected behaviour: One of the flags is "Generates no threat"

Links: https://www.wowhead.com/spell=49028/dancing-rune-weapon

**Comment by therealsmf** [comment]
that refers to the npc itself as the dk's summoned creature so that it cant get attacked back by whatever its hitting just in case it was to overaggro anything/anyone. the threat just gets added to the dk instead of any other pet generating threat like that of a hunter/warlock/etc would. considering theres a glyph to boost threat generation while its active, we can assume its working as intended.

**Comment by therealsmf** [comment]
basically it **has** to generate threat for the caster, otherwise if you were to open on an npc with this spell it wouldn't retaliate. the summoned npc does not have any threat itself, which is correct.
